# Generated by Django 4.2.7 on 2025-07-31 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('RISK_SUMMARY', 'Risk Assessment Summary'), ('APPLICATION_ANALYTICS', 'Application Analytics'), ('PERFORMANCE_METRICS', 'Performance Metrics'), ('COMPLIANCE_AUDIT', 'Compliance Audit Report'), ('FINANCIAL_OVERVIEW', 'Financial Overview'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('QUARTERLY_REPORT', 'Quarterly Report'), ('CUSTOM', 'Custom Report')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict, help_text='Report filters and parameters')),
                ('config', models.JSONField(default=dict, help_text='Report configuration settings')),
                ('data', models.JSONField(default=dict, help_text='Generated report data')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('RISK_SUMMARY', 'Risk Assessment Summary'), ('APPLICATION_ANALYTICS', 'Application Analytics'), ('PERFORMANCE_METRICS', 'Performance Metrics'), ('COMPLIANCE_AUDIT', 'Compliance Audit Report'), ('FINANCIAL_OVERVIEW', 'Financial Overview'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('QUARTERLY_REPORT', 'Quarterly Report'), ('CUSTOM', 'Custom Report')], max_length=50)),
                ('template_config', models.JSONField(default=dict)),
                ('default_filters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can use this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(default=list, help_text='Additional email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('COUNT', 'Count'), ('PERCENTAGE', 'Percentage'), ('AVERAGE', 'Average'), ('SUM', 'Sum'), ('RATIO', 'Ratio'), ('TREND', 'Trend')], max_length=50)),
                ('data_source', models.CharField(max_length=100)),
                ('calculation_method', models.TextField(help_text='SQL or calculation method')),
                ('display_format', models.CharField(default='number', max_length=50)),
                ('color_scheme', models.JSONField(default=dict)),
                ('chart_type', models.CharField(blank=True, max_length=50)),
                ('required_permissions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report KPI',
                'verbose_name_plural': 'Report KPIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment not visible to clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('SHARE', 'Shared'), ('EXPORT', 'Exported')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('export_format', models.CharField(blank=True, max_length=20)),
                ('export_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['report', 'action'], name='reports_rep_report__0fe13b_idx'), models.Index(fields=['user', 'accessed_at'], name='reports_rep_user_id_910962_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', 'created_at'], name='reports_rep_created_c4b617_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date_from', 'date_to'], name='reports_rep_date_fr_12c9d5_idx'),
        ),
    ]
