# Generated by Django 4.2.7 on 2025-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('RISK_SUMMARY', 'Risk Assessment Summary'), ('APPLICATION_ANALYTICS', 'Application Analytics'), ('PERFORMANCE_METRICS', 'Performance Metrics'), ('COMPLIANCE_AUDIT', 'Compliance Audit Report'), ('FINANCIAL_OVERVIEW', 'Financial Overview'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('QUARTERLY_REPORT', 'Quarterly Report'), ('CREDIT_SCORE_ANALYSIS', 'Credit Score Analysis'), ('DEFAULT_PREDICTION', 'Default Prediction Report'), ('PORTFOLIO_RISK', 'Portfolio Risk Analysis'), ('UNDERWRITING_PERFORMANCE', 'Underwriting Performance'), ('REGULATORY_COMPLIANCE', 'Regulatory Compliance Report'), ('LOSS_MITIGATION', 'Loss Mitigation Report'), ('CONCENTRATION_RISK', 'Concentration Risk Report'), ('MODEL_VALIDATION', 'ML Model Validation Report'), ('STRESS_TEST', 'Stress Testing Report'), ('CUSTOM', 'Custom Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('RISK_SUMMARY', 'Risk Assessment Summary'), ('APPLICATION_ANALYTICS', 'Application Analytics'), ('PERFORMANCE_METRICS', 'Performance Metrics'), ('COMPLIANCE_AUDIT', 'Compliance Audit Report'), ('FINANCIAL_OVERVIEW', 'Financial Overview'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('QUARTERLY_REPORT', 'Quarterly Report'), ('CREDIT_SCORE_ANALYSIS', 'Credit Score Analysis'), ('DEFAULT_PREDICTION', 'Default Prediction Report'), ('PORTFOLIO_RISK', 'Portfolio Risk Analysis'), ('UNDERWRITING_PERFORMANCE', 'Underwriting Performance'), ('REGULATORY_COMPLIANCE', 'Regulatory Compliance Report'), ('LOSS_MITIGATION', 'Loss Mitigation Report'), ('CONCENTRATION_RISK', 'Concentration Risk Report'), ('MODEL_VALIDATION', 'ML Model Validation Report'), ('STRESS_TEST', 'Stress Testing Report'), ('CUSTOM', 'Custom Report')], max_length=50),
        ),
    ]
