# Generated by Django 4.2.7 on 2025-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_credit_risk_report_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cache_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='cache_key',
            field=models.CharField(blank=True, help_text='Cache key for report data', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
    ]
