# Generated by Django 4.2.7 on 2025-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_ml_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('STATUS_CHANGE', 'Status Change'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('RISK_ASSESSED', 'Risk Assessed'), ('DECISION_MADE', 'Decision Made'), ('SYSTEM_ALERT', 'System Alert'), ('ML_PROCESSING_STARTED', 'ML Processing Started'), ('ML_PROCESSING_COMPLETED', 'ML Processing Completed'), ('ML_PROCESSING_FAILED', 'ML Processing Failed'), ('CREDIT_SCORE_GENERATED', 'Credit Score Generated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
