# Generated by Django 4.2.7 on 2025-05-27 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_initial'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['ANALYST', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='applications.creditapplication'),
        ),
        migrations.AddField(
            model_name='decision',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='applications.creditapplication'),
        ),
        migrations.AddField(
            model_name='decision',
            name='decision_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to='applications.applicant'),
        ),
        migrations.AddField(
            model_name='counterfactualexplanation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterfactuals', to='applications.creditapplication'),
        ),
    ]
