# Generated by Django 4.2.7 on 2025-05-27 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home Address'), ('WORK', 'Work Address'), ('OTHER', 'Other Address')], max_length=5)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('national_id', models.CharField(max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account'), ('INVESTMENT', 'Investment Account'), ('OTHER', 'Other')], max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs More Information')], default='DRAFT', max_length=15)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submission_date'],
                'permissions': [('can_assign_analyst', 'Can assign applications to analysts'), ('can_change_status', 'Can change application status')],
            },
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_bankruptcy', models.BooleanField(default=False)),
                ('bankruptcy_details', models.TextField(blank=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('credit_score_last_updated', models.DateField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='applications.applicant')),
            ],
            options={
                'verbose_name_plural': 'Financial Information',
            },
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('SELF_EMPLOYED', 'Self-employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_verified', models.BooleanField(default=False)),
                ('verification_documents', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='applications.applicant')),
            ],
            options={
                'verbose_name_plural': 'Employment Information',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'Identification'), ('PROOF_OF_INCOME', 'Proof of Income'), ('TAX_RETURN', 'Tax Return'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.creditapplication')),
            ],
        ),
    ]
