# Generated by Django 4.2.7 on 2025-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ID', 'Identification'), ('PROOF_OF_INCOME', 'Proof of Income'), ('TAX_RETURN', 'Tax Return'), ('BANK_STATEMENT', 'Bank Statement'), ('CREDIT_REPORT', 'Credit Report'), ('PROPERTY_DEED', 'Property Deed'), ('BUSINESS_REGISTRATION', 'Business Registration'), ('INSURANCE_DOCUMENT', 'Insurance Document'), ('OTHER', 'Other')], max_length=25),
        ),
    ]
