# Generated by Django 4.2.7 on 2025-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_creditapplication_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='collections_12mo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='credit_history_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='debt_to_income_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='delinquencies_2yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='employment_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='home_ownership',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='inquiries_6mo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='max_bankcard_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='open_accounts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='public_records',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='revolving_accounts_12mo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='revolving_utilization',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='total_accounts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
