# Generated by Django 4.2.7 on 2025-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_creditapplication_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title for Ghana employment analysis (emp_title field)', max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentinfo',
            name='job_title',
            field=models.CharField(help_text='Job title for employment record', max_length=100),
        ),
    ]
