# Generated by Django 4.2.7 on 2025-08-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_job_title_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLCreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(help_text='Predicted credit score (300-850)')),
                ('category', models.CharField(help_text='Poor, Fair, Good, Very Good, Exceptional', max_length=20)),
                ('risk_level', models.CharField(help_text='Very High Risk, High Risk, Medium Risk, Low Risk', max_length=20)),
                ('confidence', models.FloatField(help_text='Prediction confidence percentage')),
                ('ghana_job_category', models.CharField(blank=True, help_text='Categorized job type', max_length=50, null=True)),
                ('ghana_employment_score', models.FloatField(blank=True, help_text='Employment stability score', null=True)),
                ('ghana_job_stability_score', models.IntegerField(blank=True, help_text='Job stability score (20-85/100)', null=True)),
                ('model_version', models.CharField(default='2.0.0', max_length=20)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_accuracy', models.FloatField(default=98.4, help_text='Model R² accuracy')),
                ('confidence_factors', models.JSONField(blank=True, help_text='Detailed confidence analysis', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Prediction processing time in milliseconds', null=True)),
                ('features_used', models.JSONField(blank=True, help_text='Features used for prediction', null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_assessment', to='applications.creditapplication')),
            ],
            options={
                'verbose_name': 'ML Credit Assessment',
                'verbose_name_plural': 'ML Credit Assessments',
                'db_table': 'ml_credit_assessments',
                'ordering': ['-prediction_timestamp'],
            },
        ),
    ]
