# Generated by Django 4.2.7 on 2025-08-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_add_ml_credit_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
