# Generated by Django 5.2.5 on 2025-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_creditapplication_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='reference_number',
            field=models.CharField(default='REF-DEFAULT', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
