# Generated by Django 4.2.7 on 2025-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_creditapplication_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlcreditassessment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time this assessment was updated'),
        ),
        migrations.AddField(
            model_name='mlcreditassessment',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='mlcreditassessment',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='COMPLETED', help_text='Current processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='mlcreditassessment',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of processing retries'),
        ),
    ]
