# Generated by Django 4.2.7 on 2025-09-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0012_alter_creditapplication_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs More Information')], max_length=15, null=True)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs More Information')], max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('system_generated', models.BooleanField(default=False, help_text='True if status change was automatic')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.creditapplication')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['application', '-changed_at'], name='application_applica_64175c_idx'), models.Index(fields=['new_status', '-changed_at'], name='application_new_sta_119221_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=15)),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request More Information'), ('ESCALATE', 'Escalate to Senior Analyst')], max_length=15, null=True)),
                ('risk_assessment_score', models.IntegerField(blank=True, help_text='Risk score (1-100)', null=True)),
                ('creditworthiness_rating', models.CharField(blank=True, help_text='Overall creditworthiness', max_length=20)),
                ('general_remarks', models.TextField(blank=True, help_text='General comments about the application')),
                ('strengths', models.TextField(blank=True, help_text='Positive aspects of the application')),
                ('concerns', models.TextField(blank=True, help_text='Areas of concern or risk')),
                ('recommendation', models.TextField(blank=True, help_text='Final recommendation')),
                ('additional_info_required', models.TextField(blank=True, help_text='Details of additional information needed')),
                ('documents_required', models.JSONField(blank=True, default=list, help_text='List of additional documents needed')),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('review_completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_processing_days', models.IntegerField(blank=True, help_text='Estimated days to complete', null=True)),
                ('requires_second_opinion', models.BooleanField(default=False)),
                ('second_review_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='applications.creditapplication')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['ANALYST', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_reviews', to=settings.AUTH_USER_MODEL)),
                ('second_reviewer', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['ANALYST', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_status', '-created_at'], name='application_review__593ae6_idx'), models.Index(fields=['reviewer', '-created_at'], name='application_reviewe_7ce70a_idx'), models.Index(fields=['decision'], name='application_decisio_151120_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('INTERNAL', 'Internal Note'), ('CLIENT_VISIBLE', 'Visible to Client'), ('CLIENT_MESSAGE', 'Message from Client'), ('SYSTEM', 'System Generated')], default='INTERNAL', max_length=15)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False, help_text='For client messages - has analyst read this?')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comment_attachments/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.creditapplication')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='applications.applicationcomment')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_54685b_idx'), models.Index(fields=['comment_type', '-created_at'], name='application_comment_fc43f4_idx'), models.Index(fields=['author', '-created_at'], name='application_author__2dc91d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Application Created'), ('SUBMITTED', 'Application Submitted'), ('STATUS_CHANGED', 'Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('REVIEW_STARTED', 'Review Started'), ('REVIEW_COMPLETED', 'Review Completed'), ('COMMENT_ADDED', 'Comment Added'), ('ASSIGNED', 'Assigned to Analyst'), ('ML_ASSESSMENT', 'ML Assessment Generated'), ('NOTIFICATION_SENT', 'Notification Sent')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='applications.creditapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_254db8_idx'), models.Index(fields=['activity_type', '-created_at'], name='application_activit_3bb014_idx'), models.Index(fields=['user', '-created_at'], name='application_user_id_b0153e_idx')],
            },
        ),
    ]
