version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  # celery-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: celery-worker
  #   command: celery -A backend worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   restart: unless-stopped

  # celery-beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: celery-beat
  #   command: celery -A backend beat --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
