# Generated by Django 4.2.7 on 2025-06-16 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_timestamp']},
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='session_key',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='login_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='was_successful',
            field=models.BooleanField(),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'login_timestamp'], name='users_login_user_id_10db18_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', 'login_timestamp'], name='users_login_ip_addr_2b0a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['was_successful', 'login_timestamp'], name='users_login_was_suc_f9b3f2_idx'),
        ),
    ]
