# Generated by Django 4.2.7 on 2025-07-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permission_role_userrole_permissionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='decsription',
            new_name='description',
        ),
    ]
