# Generated by Django 4.2.7 on 2025-08-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when MFA setup was completed', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_setup_pending',
            field=models.BooleanField(default=False, help_text="True if user requested MFA but hasn't completed setup"),
        ),
    ]
