# Generated by Django 4.2.7 on 2025-08-01 16:05

from django.db import migrations
from django.utils import timezone


def update_existing_mfa_users(apps, schema_editor):
    """
    Update existing users with MFA enabled to have proper completion status.
    Users who already have mfa_enabled=True and mfa_secret should be marked as completed.
    """
    User = apps.get_model('users', 'User')
    
    # Find users who have MFA enabled and have a secret
    users_with_completed_mfa = User.objects.filter(
        mfa_enabled=True,
        mfa_secret__isnull=False
    ).exclude(mfa_secret='')
    
    # Mark them as completed
    completed_count = 0
    for user in users_with_completed_mfa:
        user.mfa_setup_pending = False
        user.mfa_completed_at = timezone.now()
        user.save(update_fields=['mfa_setup_pending', 'mfa_completed_at'])
        completed_count += 1
    
    # Find users who have MFA enabled but no secret (incomplete state)
    users_with_incomplete_mfa = User.objects.filter(
        mfa_enabled=True,
        mfa_secret__isnull=True
    ) | User.objects.filter(
        mfa_enabled=True,
        mfa_secret=''
    )
    
    # Reset their MFA state to prevent security issues
    incomplete_count = 0
    for user in users_with_incomplete_mfa:
        user.mfa_enabled = False
        user.mfa_setup_pending = False  # They'll need to request MFA again
        user.mfa_completed_at = None
        user.save(update_fields=['mfa_enabled', 'mfa_setup_pending', 'mfa_completed_at'])
        incomplete_count += 1
    
    print(f"Migration completed:")
    print(f"  - {completed_count} users marked as having completed MFA")
    print(f"  - {incomplete_count} users with incomplete MFA state reset")


def reverse_update_existing_mfa_users(apps, schema_editor):
    """
    Reverse the migration by clearing the new fields.
    """
    User = apps.get_model('users', 'User')
    
    User.objects.all().update(
        mfa_setup_pending=False,
        mfa_completed_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_mfa_completion_fields'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_mfa_users,
            reverse_update_existing_mfa_users,
        ),
    ]
