# Generated by Django 4.2.7 on 2025-08-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_update_existing_mfa_users'),
    ]

    operations = [
    ]
