# Generated by Django 4.2.7 on 2025-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20250801_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_admin',
            field=models.BooleanField(default=False, help_text='True if user was created by admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temp_password',
            field=models.BooleanField(default=False, help_text='True if current password is temporary'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='True if user must change password on next login'),
        ),
    ]
