# Generated by Django 4.2.7 on 2025-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_temporary_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ghana_card_extracted_name',
            field=models.CharField(blank=True, help_text='Name extracted from Ghana Card using OCR', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_image',
            field=models.ImageField(blank=True, help_text='Ghana Card image for verification', null=True, upload_to='ghana_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_name_verified',
            field=models.BooleanField(default=False, help_text='True if name on Ghana Card matches profile name'),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, help_text='Ghana Card ID number', max_length=20),
        ),
    ]
