# Generated by Django 4.2.7 on 2025-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_ghana_card_extracted_name_user_ghana_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, db_index=True, help_text='Ghana Card ID number', max_length=20),
        ),
    ]
