# Generated by Django 4.2.7 on 2025-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_ghana_card_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ghana_card_image',
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_back_image',
            field=models.ImageField(blank=True, help_text='Ghana Card back image (with ID number and address)', null=True, upload_to='ghana_cards/back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_extracted_number',
            field=models.CharField(blank=True, help_text='ID number extracted from Ghana Card back using OCR', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_front_image',
            field=models.ImageField(blank=True, help_text='Ghana Card front image (with photo and name)', null=True, upload_to='ghana_cards/front/'),
        ),
        migrations.AddField(
            model_name='user',
            name='ghana_card_number_verified',
            field=models.BooleanField(default=False, help_text='True if Ghana Card number was successfully extracted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ghana_card_extracted_name',
            field=models.CharField(blank=True, help_text='Name extracted from Ghana Card front using OCR', max_length=300),
        ),
    ]
