# Generated by Django 4.2.7 on 2025-08-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_github_url_userprofile_portfolio_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Professional website/portfolio URL'),
        ),
    ]
